from random import randint

def sample_module() -> int:
    """This sample module just returns a random 2 digit integer.
    
    Args:
        None

    Returns:
        int: A random 2-digit integer generated by this funtion.
    """    
    return randint(10, 100)
